version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./kafka-logs:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 10s
      retries: 5

  producer:
    build:
      context: .
      dockerfile: ./kafka_stream.Dockerfile
    container_name: producer
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
    command: python kafka_stream.py

  spark:
    image: bitnami/spark:latest
    container_name: spark
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      MODEL_PATH: /app/model
      KAFKA_SERVER: kafka:9092
    command: bash -c "
      pip install --no-cache-dir -r /app/requirements.txt && \
      spark-submit  --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 /app/online_inference.py
      "
